name: pull

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions: read-all

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - run: rustup update --no-self-update stable && rustup default stable
      - run: make check
      - run: make test
